/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define ADC1_BASE_ADDR			0x40012000UL
#define ADC_CR1_OFFSET			0x04UL
#define ADC_CR1_ADDR			(ADC1_BASE_ADDR + ADC_CR1_OFFSET)

#define RCC_BASE_ADDRESS		0x40023800UL
#define RCC_APB2ENR_OFFSET		0x44UL
#define RCC_APB2ENR_ADDR		(RCC_BASE_ADDRESS + RCC_APB2ENR_OFFSET)

int main(void)
{
	uint32_t *pRccApb2Enr = (uint32_t *)RCC_APB2ENR_ADDR;
	uint32_t *pAdcCr1Scan = (uint32_t *)ADC_CR1_ADDR;

	// Enable clock for ADC1
	*pRccApb2Enr |= (1 << 8);

	// Enable scan bit of ADC_CR1
	*pAdcCr1Scan |= (1 << 8);

    /* Loop forever */
	for(;;);
}
